workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        CM_KEY_ALIAS: upload
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/android/app/upload-keystore.jks
          printf "storePassword=$CM_KEYSTORE_PASSWORD\nkeyPassword=$CM_KEY_PASSWORD\nkeyAlias=$CM_KEY_ALIAS\nstoreFile=upload-keystore.jks\n" > $CM_BUILD_DIR/android/key.properties
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - ysseo.max@gmail.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Release Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      vars:
        BUNDLE_ID: com.mobilecontent.mobileContent
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
    scripts:
      - name: Get Flutter packages and install CocoaPods
        script: |
          flutter packages pub get
          flutter precache --ios
          flutter pub get
          cd ios && pod install
      - name: Generate certificate key and fetch signing files
        script: |
          set -e
          openssl genrsa -out /tmp/cert_key.pem 2048
          export CERTIFICATE_PRIVATE_KEY=$(cat /tmp/cert_key.pem)
          # Persist CERTIFICATE_PRIVATE_KEY for subsequent steps
          echo "CERTIFICATE_PRIVATE_KEY<<CERTEOF" >> $CM_ENV
          cat /tmp/cert_key.pem >> $CM_ENV
          echo "CERTEOF" >> $CM_ENV
          # Revoke existing distribution certificates (new key won't match old certs)
          echo "=== Revoking old certificates ==="
          app-store-connect certificates list --type DISTRIBUTION --json > /tmp/certs.json 2>/dev/null || echo "[]" > /tmp/certs.json
          echo "Certificate JSON structure:"
          cat /tmp/certs.json | python3 -m json.tool 2>/dev/null | head -40
          python3 -c "
          import json, subprocess
          try:
              certs = json.load(open('/tmp/certs.json'))
              for c in certs:
                  print(f'Keys: {list(c.keys())}')
                  # Try multiple possible ID fields
                  cert_id = c.get('id') or c.get('serialNumber') or c.get('serial_number') or c.get('certificateId') or ''
                  print(f'Revoking cert id: {cert_id}')
                  if cert_id:
                      subprocess.run(['app-store-connect','certificates','delete',str(cert_id)], check=False)
          except Exception as e:
              print(f'Error: {e}')
          "
          echo "=== Fetching signing files ==="
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up keychain and signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles
          # Debug: show keychain and identities
          security list-keychains
          security find-identity -v -p codesigning
      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign
      - name: Archive and export IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
      - name: Publish to App Store Connect
        script: |
          app-store-connect publish \
            --path build/ios/ipa/*.ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ysseo.max@gmail.com
        notify:
          success: true
          failure: true
