workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        CM_KEY_ALIAS: upload
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/android/app/upload-keystore.jks
          printf "storePassword=$CM_KEYSTORE_PASSWORD\nkeyPassword=$CM_KEY_PASSWORD\nkeyAlias=$CM_KEY_ALIAS\nstoreFile=upload-keystore.jks\n" > $CM_BUILD_DIR/android/key.properties
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - ysseo.max@gmail.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Release Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      vars:
        BUNDLE_ID: com.mobilecontent.mobileContent
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
    scripts:
      - name: Get Flutter packages and install CocoaPods
        script: |
          flutter packages pub get
          flutter precache --ios
          flutter pub get
          cd ios && pod install
      - name: Generate certificate key and fetch signing files
        script: |
          set -e
          openssl genrsa -out /tmp/cert_key.pem 2048
          export CERTIFICATE_PRIVATE_KEY=$(cat /tmp/cert_key.pem)
          # List existing distribution certificates
          echo "=== Listing existing certificates ==="
          app-store-connect certificates list --type DISTRIBUTION --json > /tmp/certs.json || true
          cat /tmp/certs.json || true
          # Revoke all existing distribution certificates (unusable without original private keys)
          python3 -c "
          import json, subprocess, sys
          try:
              with open('/tmp/certs.json') as f:
                  certs = json.load(f)
              for cert in certs:
                  serial = cert.get('serialNumber') or cert.get('id') or cert.get('serial_number', '')
                  name = cert.get('name', cert.get('displayName', 'unknown'))
                  print(f'Revoking certificate: {name} (serial: {serial})')
                  subprocess.run(['app-store-connect', 'certificates', 'delete', serial], check=False)
          except Exception as e:
              print(f'Certificate cleanup: {e}')
          "
          echo "=== Fetching signing files ==="
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up signing
        script: |
          keychain add-certificates
          xcode-project use-profiles
      - name: Flutter build without codesign
        script: flutter build ios --release --no-codesign
      - name: Build IPA with xcode-project
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ysseo.max@gmail.com
        notify:
          success: true
          failure: true
