workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        CM_KEY_ALIAS: upload
    scripts:
      - name: Set up keystore
        script: |
          set -e
          # Decode base64 keystore with Python (reliable padding handling)
          python3 << 'PYEOF'
          import base64, os, sys
          raw = os.environ['CM_KEYSTORE']
          data = base64.b64decode(raw + '=' * (-len(raw) % 4))
          sys.stderr.write('Keystore: %d bytes, header=%s\n' % (len(data), data[:4].hex()))
          with open('/tmp/ks_src.ks', 'wb') as f:
              f.write(data)
          PYEOF

          # Resolve keytool from JDK
          KEYTOOL="${JAVA_HOME}/bin/keytool"
          [ -x "$KEYTOOL" ] || KEYTOOL=$(which keytool)
          echo "=== Using keytool: $KEYTOOL ==="

          # Convert PKCS12 → JKS (bundletool in AGP 8.x requires JKS)
          "$KEYTOOL" -importkeystore \
            -srckeystore /tmp/ks_src.ks \
            -srcstoretype PKCS12 \
            -srcstorepass "$CM_KEYSTORE_PASSWORD" \
            -destkeystore "$CM_BUILD_DIR/android/app/upload-keystore.jks" \
            -deststoretype JKS \
            -deststorepass "$CM_KEYSTORE_PASSWORD" \
            -destkeypass "$CM_KEY_PASSWORD" \
            -noprompt

          # Verify JKS output
          echo "=== JKS keystore created ==="
          ls -la "$CM_BUILD_DIR/android/app/upload-keystore.jks"
          "$KEYTOOL" -list -storetype JKS \
            -keystore "$CM_BUILD_DIR/android/app/upload-keystore.jks" \
            -storepass "$CM_KEYSTORE_PASSWORD" 2>&1 | head -8

          printf "storePassword=%s\nkeyPassword=%s\nkeyAlias=%s\nstoreFile=upload-keystore.jks\n" \
            "$CM_KEYSTORE_PASSWORD" "$CM_KEY_PASSWORD" "$CM_KEY_ALIAS" \
            > "$CM_BUILD_DIR/android/key.properties"
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - ysseo.max@gmail.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Release Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      vars:
        BUNDLE_ID: com.mobilecontent.mobileContent
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
    scripts:
      - name: Get Flutter packages and install CocoaPods
        script: |
          flutter packages pub get
          flutter precache --ios
          flutter pub get
          cd ios && pod install
      - name: Generate certificate key and fetch signing files
        script: |
          set -e
          openssl genrsa -out /tmp/cert_key.pem 2048
          export CERTIFICATE_PRIVATE_KEY=$(cat /tmp/cert_key.pem)
          echo "CERTIFICATE_PRIVATE_KEY<<CERTEOF" >> $CM_ENV
          cat /tmp/cert_key.pem >> $CM_ENV
          echo "CERTEOF" >> $CM_ENV
          echo "=== Revoking old certificates ==="
          app-store-connect certificates list --type DISTRIBUTION --json > /tmp/certs.json 2>/dev/null || echo "[]" > /tmp/certs.json
          python3 << 'PYEOF'
          import json, subprocess
          try:
              certs = json.load(open('/tmp/certs.json'))
              for c in certs:
                  cert_id = c.get('id') or c.get('serialNumber') or c.get('certificateId') or ''
                  if cert_id:
                      print(f'Revoking cert: {cert_id}')
                      subprocess.run(['app-store-connect','certificates','delete',str(cert_id)], check=False)
          except Exception as e:
              print(f'Cert revocation error: {e}')
          PYEOF
          echo "=== Fetching signing files ==="
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up keychain and signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles
          security list-keychains
          security find-identity -v -p codesigning
      - name: Build iOS (no codesign)
        script: |
          xcodebuild -version
          flutter build ios --release --no-codesign --verbose 2>&1 | tail -100
      - name: Archive and export IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
      - name: Publish to App Store Connect
        script: |
          app-store-connect publish \
            --path build/ios/ipa/*.ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ysseo.max@gmail.com
        notify:
          success: true
          failure: true
