workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        CM_KEY_ALIAS: upload
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/android/app/upload-keystore.jks
          printf "storePassword=$CM_KEYSTORE_PASSWORD\nkeyPassword=$CM_KEY_PASSWORD\nkeyAlias=$CM_KEY_ALIAS\nstoreFile=upload-keystore.jks\n" > $CM_BUILD_DIR/android/key.properties
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - ysseo.max@gmail.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Release Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      vars:
        BUNDLE_ID: com.mobilecontent.mobileContent
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
    scripts:
      - name: Get Flutter packages and install CocoaPods
        script: |
          flutter packages pub get
          flutter precache --ios
          flutter pub get
          cd ios && pod install
      - name: Generate certificate private key
        script: |
          openssl req -nodes -newkey rsa:2048 -keyout /tmp/cert_key.pem -out /tmp/cert_key.csr \
            -subj "/CN=iOS Distribution/O=Mobile Content/C=KR"
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --certificate-key /tmp/cert_key.pem
      - name: Set up signing
        script: |
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ysseo.max@gmail.com
        notify:
          success: true
          failure: true
